<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5d616fa4-ab42-4694-9a34-0b05ae6573c7</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentAPI.DAL\PaymentAPI.DAL.csproj" />
    <ProjectReference Include="..\PaymentAPI.Domain\PaymentAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\taras_kuznietsov\Desktop\C# course\events_bookings\PaymentAPI\PaymentAPI\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\taras_kuznietsov\Desktop\C# course\events_bookings\PaymentAPI\PaymentAPI\.editorconfig" />
  </ItemGroup>

</Project>
